### ISSUE TITLE
Feat: Create `Flutter` Stopwatch Tutorial

### ISSUE THREAD

**Issue by nelsonic** [dwyl/flutter-stopwatch-tutorial#1]
One of the "core" features of our **`App`** is **`timers`**, see: [mvp.fly.dev](https://github.com/dwyl/mvp/issues/140) 📱 
At its' core the **`timer`** feature is a stopwatch. ⏱️ 

# Todo

+ [x] Create a **`Flutter`** tutorial similar to: https://github.com/dwyl/phoenix-liveview-stopwatch
+ [x] Take the reader from zero to working App on a ***Mobile Device*** in as much detail as necessary
+ [x] Bonus Level: Persistence e.g: using `drift` https://github.com/dwyl/learn-flutter/issues/70 to have a _history_ of the timers you have captured on the device.

**Comment by LuchoTurtle** [comment]
The referenced PR https://github.com/dwyl/flutter-stopwatch-tutorial/pull/2 should close this issue and I think it's completed. The project works as "advertised" and the README should thoroughly explain how to get the app working 😄
